export const FETCH_STOCK_DATA = "FETCH_STOCK_DATA";
export const SORT_STOCK_DATA = "SORT_STOCK_DATA";

export const EXPORT_STOCK_DATA_REQUEST = "EXPORT_STOCK_DATA_REQUEST";
export const EXPORT_STOCK_DATA_SUCCESS = "EXPORT_STOCK_DATA_SUCCESS";
export const EXPORT_STOCK_DATA_FAILURE = "EXPORT_STOCK_DATA_FAILURE";

export const FETCH_STOCK_DATA_REQUEST = "FETCH_STOCK_DATA_REQUEST";
export const FETCH_STOCK_DATA_SUCCESS = "FETCH_STOCK_DATA_SUCCESS";
export const FETCH_STOCK_DATA_FAILURE = "FETCH_STOCK_DATA_FAILURE";