export const FETCH_STOCK_DATA = "FETCH_STOCK_DATA";
export const SORT_STOCK_DATA = "SORT_STOCK_DATA";
export const EXPORT_STOCK_FILE = "EXPORT_STOCK_FILE";

export const FETCH_STOCK_DATA_REQUEST = "FETCH_STOCK_DATA_REQUEST";
export const FETCH_STOCK_DATA_SUCCESS = "FETCH_STOCK_DATA_SUCCESS";
export const FETCH_STOCK_DATA_FAILURE = "FETCH_STOCK_DATA_FAILURE";